import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server.mjs';
test('HTTP: Anmeldung, Gerätesynchronisierung, Konflikte, CSRF und private Bilder', async t => {
  const directory = mkdtempSync(join(tmpdir(), 'family-http-'));
  const app = createApp({ DATA_DIR: directory });
  await new Promise(r => app.server.listen(0, '127.0.0.1', r));
  const base = `http://127.0.0.1:${app.server.address().port}`;
  t.after(async () => { await new Promise(r => app.server.close(r)); app.store.close(); rmSync(directory, { recursive: true, force: true }); });
  let cookie;
  const request = (path, method = 'GET', data, additional = {}) => fetch(base + path, { method, headers: { 'X-Family-Request': '1', 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}), ...additional }, ...(data !== undefined ? { body: JSON.stringify(data) } : {}) });
  assert.equal((await request('/api/state')).status, 401);
  const setup = await request('/api/setup', 'POST', { password: 'test-password-2026', familyName: 'Familie Test', names: ['Anna', 'Ben'], demo: false });
  assert.equal(setup.status, 201); cookie = setup.headers.get('set-cookie').split(';')[0];
  assert.match(setup.headers.get('set-cookie'), /HttpOnly/);
  assert.equal((await request('/api/setup', 'POST', {})).status, 409);
  const initial = await (await request('/api/state')).json(); assert.equal(initial.members.length, 2);
  const response = await request('/api/records/notes', 'POST', { title: '<script>alert(1)</script>', body: 'Gemeinsam' });
  const note = await response.json(); assert.equal(response.status, 201);
  const device2 = await request('/api/login', 'POST', { password: 'test-password-2026' });
  const cookie2 = device2.headers.get('set-cookie').split(';')[0];
  const secondState = await (await request('/api/state', 'GET', undefined, { Cookie: cookie2 })).json(); assert.equal(secondState.notes[0].body, 'Gemeinsam');
  assert.equal((await request('/api/records/notes/' + note.id, 'PUT', { ...note, body: 'Neu' })).status, 200);
  assert.equal((await request('/api/records/notes/' + note.id, 'PUT', { ...note, body: 'Veraltet' })).status, 409);
  assert.equal((await request('/api/records/notes', 'POST', { title: 'CSRF' }, { Origin: 'https://foreign.example' })).status, 403);
  assert.equal((await fetch(base + '/api/records/notes', { method: 'POST', headers: { Cookie: cookie, 'Content-Type': 'application/json' }, body: '{}' })).status, 403);
  const photo = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+yG90AAAAASUVORK5CYII=', 'base64');
  const uploaded = await fetch(base + '/api/photos/upload', { method: 'POST', headers: { Cookie: cookie, 'X-Family-Request': '1', 'Content-Type': 'image/png' }, body: photo });
  assert.equal(uploaded.status, 201); const image = await uploaded.json();
  assert.equal((await request(image.url)).status, 200); assert.equal((await fetch(base + image.url)).status, 401);
  assert.equal((await request('/api/photos/file?file=..%2Fmaster.key')).status, 404);
  writeFileSync(join(directory, 'outside.png'), photo); symlinkSync(join(directory, 'outside.png'), join(directory, 'photos', 'link.png'));
  assert.equal((await request('/api/photos/file?file=link.png')).status, 404);
  assert.ok(!(await (await request('/api/photos')).json()).some(i => i.id === 'link.png'));
  const exportText = await (await request('/api/export')).text(); assert.ok(!exportText.includes('test-password-2026')); assert.ok(!exportText.includes('salt'));
  assert.equal((await request('/api/password', 'POST', { currentPassword: 'test-password-2026', newPassword: 'new-password-2026' })).status, 200);
  assert.equal((await request('/api/state', 'GET', undefined, { Cookie: cookie2 })).status, 401);
});
