import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server.mjs';
import { parseRecipePage } from '../src/recipe-import.mjs';
test('HTTP: Elternpasswort schützt Punkte und Updates; Aufgabenbilder und Mehrfachzuordnungen bleiben in der Familie', async t => {
  const directory = mkdtempSync(join(tmpdir(), 'family-admin-')); let updateStarts = 0;
  const app = createApp({ DATA_DIR: directory }, { updater: { status: async () => ({ supported: true, phase: 'idle' }), start: async () => { updateStarts++; return { supported: true, phase: 'backup', active: true }; } } });
  await new Promise(resolve => app.server.listen(0, '127.0.0.1', resolve));
  t.after(async () => { await new Promise(resolve => app.server.close(resolve)); app.store.close(); rmSync(directory, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${app.server.address().port}`; let cookie;
  const request = (path, method = 'GET', data) => fetch(base + path, { method, headers: { 'X-Family-Request': '1', 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}) }, ...(data ? { body: JSON.stringify(data) } : {}) });
  assert.equal((await request('/api/updates/status')).status, 401);
  const setup = await request('/api/setup', 'POST', { password: 'family-password-fixture', names: ['Anna', 'Ben'] }); cookie = setup.headers.get('set-cookie').split(';')[0];
  const state = await (await request('/api/state')).json(), memberIds = state.members.map(m => m.id);
  assert.equal((await request('/api/updates/start', 'POST', { password: 'missing' })).status, 403); assert.equal(updateStarts, 0);
  const password = { familyPassword: 'family-password-fixture', newPassword: 'parent-secret-fixture', confirmPassword: 'parent-secret-fixture' };
  assert.equal((await request('/api/parent-password', 'PUT', { ...password, familyPassword: 'wrong' })).status, 403);
  assert.equal((await request('/api/parent-password', 'PUT', password)).status, 200);
  assert.equal((await request('/api/parent-password', 'PUT', password)).status, 403);
  const grant = { memberId: memberIds[0], points: 15, reason: 'Geholfen', requestId: 'abcdefabcdef1234', password: 'parent-secret-fixture' };
  assert.equal((await request('/api/points/award', 'POST', { ...grant, password: 'wrong' })).status, 403);
  assert.equal((await request('/api/points/award', 'POST', grant)).status, 201); assert.equal((await request('/api/points/award', 'POST', grant)).status, 201);
  assert.equal((await request('/api/updates/start', 'POST', { password: 'wrong' })).status, 403);
  assert.equal((await request('/api/updates/start', 'POST', { password: grant.password })).status, 202); assert.equal(updateStarts, 1);
  assert.equal((await request('/api/records/pointAwards', 'POST', grant)).status, 404);
  const exported = await (await request('/api/export')).json(); assert.equal(exported.points[memberIds[0]].available, 15); assert.equal(exported.parentPasswordConfigured, true);
  assert.ok(!JSON.stringify(exported).includes(grant.password)); assert.ok(!JSON.stringify(exported).includes(app.store.meta('parentPassword').hash));
  const event = await request('/api/records/events', 'POST', { title: 'Fitness', startDate: state.serverDate, startTime: '07:00', startOnly: true, memberIds }); assert.equal(event.status, 201); assert.deepEqual((await event.json()).memberIds, memberIds);
  const photo = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+yG90AAAAASUVORK5CYII=', 'base64');
  const upload = await fetch(base + '/api/tasks/image', { method: 'POST', headers: { Cookie: cookie, 'X-Family-Request': '1' }, body: photo }); assert.equal(upload.status, 201); const image = await upload.json();
  assert.equal((await fetch(base + '/api/tasks/image?file=' + image.imageFile)).status, 401);
  assert.equal((await request('/api/tasks/image?file=' + image.imageFile)).status, 200);
  assert.equal((await request('/api/tasks/image?file=../master.key')).status, 404);
  const taskResponse = await request('/api/records/tasks', 'POST', { title: 'Spülmaschine', imageFile: image.imageFile, points: 5 }); const task = await taskResponse.json();
  assert.equal((await request(`/api/tasks/${task.id}/assign`, 'POST', { _rev: task._rev, memberId: memberIds[1], date: state.serverDate })).status, 200);
  assert.equal((await request(`/api/tasks/${task.id}/assign`, 'POST', { _rev: task._rev, memberId: memberIds[0], date: state.serverDate })).status, 409);
  assert.equal((await request(`/api/tasks/${task.id}/complete`, 'POST', { date: state.serverDate, done: true })).status, 200);
  assert.equal((await (await request('/api/state')).json()).points[memberIds[1]].available, 5);
});
test('HTTP: Anmeldung, Gerätesynchronisierung, Konflikte, CSRF und private Bilder', async t => {
  const directory = mkdtempSync(join(tmpdir(), 'family-http-'));
  const app = createApp({ DATA_DIR: directory });
  await new Promise(r => app.server.listen(0, '127.0.0.1', r));
  const base = `http://127.0.0.1:${app.server.address().port}`;
  t.after(async () => { await new Promise(r => app.server.close(r)); app.store.close(); rmSync(directory, { recursive: true, force: true }); });
  let cookie;
  const request = (path, method = 'GET', data, additional = {}) => fetch(base + path, { method, headers: { 'X-Family-Request': '1', 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}), ...additional }, ...(data !== undefined ? { body: JSON.stringify(data) } : {}) });
  assert.equal((await request('/api/state')).status, 401);
  const setup = await request('/api/setup', 'POST', { password: 'test-password-2026', familyName: 'Familie Test', names: ['Anna', 'Ben'], demo: false });
  assert.equal(setup.status, 201); cookie = setup.headers.get('set-cookie').split(';')[0];
  assert.match(setup.headers.get('set-cookie'), /HttpOnly/);
  assert.equal((await request('/api/setup', 'POST', {})).status, 409);
  const initial = await (await request('/api/state')).json(); assert.equal(initial.members.length, 2);
  const response = await request('/api/records/notes', 'POST', { title: '<script>alert(1)</script>', body: 'Gemeinsam' });
  const note = await response.json(); assert.equal(response.status, 201);
  const device2 = await request('/api/login', 'POST', { password: 'test-password-2026' });
  const cookie2 = device2.headers.get('set-cookie').split(';')[0];
  const secondState = await (await request('/api/state', 'GET', undefined, { Cookie: cookie2 })).json(); assert.equal(secondState.notes[0].body, 'Gemeinsam');
  assert.equal((await request('/api/records/notes/' + note.id, 'PUT', { ...note, body: 'Neu' })).status, 200);
  assert.equal((await request('/api/records/notes/' + note.id, 'PUT', { ...note, body: 'Veraltet' })).status, 409);
  assert.equal((await request('/api/records/notes', 'POST', { title: 'CSRF' }, { Origin: 'https://foreign.example' })).status, 403);
  assert.equal((await fetch(base + '/api/records/notes', { method: 'POST', headers: { Cookie: cookie, 'Content-Type': 'application/json' }, body: '{}' })).status, 403);
  const photo = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+yG90AAAAASUVORK5CYII=', 'base64');
  const uploaded = await fetch(base + '/api/photos/upload', { method: 'POST', headers: { Cookie: cookie, 'X-Family-Request': '1', 'Content-Type': 'image/png' }, body: photo });
  assert.equal(uploaded.status, 201); const image = await uploaded.json();
  assert.equal((await request(image.url)).status, 200); assert.equal((await fetch(base + image.url)).status, 401);
  assert.equal((await request('/api/photos/file?file=..%2Fmaster.key')).status, 404);
  writeFileSync(join(directory, 'outside.png'), photo); symlinkSync(join(directory, 'outside.png'), join(directory, 'photos', 'link.png'));
  assert.equal((await request('/api/photos/file?file=link.png')).status, 404);
  assert.ok(!(await (await request('/api/photos')).json()).some(i => i.id === 'link.png'));
  const exportText = await (await request('/api/export')).text(); assert.ok(!exportText.includes('test-password-2026')); assert.ok(!exportText.includes('salt'));
  assert.equal((await request('/api/password', 'POST', { currentPassword: 'test-password-2026', newPassword: 'new-password-2026' })).status, 200);
  assert.equal((await request('/api/state', 'GET', undefined, { Cookie: cookie2 })).status, 401);
});

test('HTTP: Geburtstage sind synchronisiert; Rezeptimport bleibt bis zum Speichern eine geschützte Vorschau', async t => {
  const directory = mkdtempSync(join(tmpdir(), 'family-features-'));
  let imports = 0;
  const app = createApp({ DATA_DIR: directory }, { importRecipe: async url => {
    imports++;
    return parseRecipePage(JSON.stringify({ '@type': 'Recipe', name: 'Eigene Testpasta', recipeYield: '4 Portionen', totalTime: 'PT20M', recipeIngredient: ['400 g Nudeln'], recipeInstructions: 'Nudeln kochen.' }), url);
  } });
  await new Promise(resolve => app.server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${app.server.address().port}`;
  t.after(async () => { await new Promise(resolve => app.server.close(resolve)); app.store.close(); rmSync(directory, { recursive: true, force: true }); });
  let cookie = '';
  const request = (path, method = 'GET', data, extra = {}) => fetch(base + path, { method, headers: { 'X-Family-Request': '1', 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}), ...extra }, ...(data ? { body: JSON.stringify(data) } : {}) });
  assert.equal((await request('/api/recipes/import', 'POST', { url: 'https://rezepte.example/pasta' })).status, 401); assert.equal(imports, 0);
  const setup = await request('/api/setup', 'POST', { password: 'test-password-2026', familyName: 'Test', names: ['Anna'] });
  cookie = setup.headers.get('set-cookie').split(';')[0];
  const initial = await (await request('/api/state')).json(); assert.deepEqual(initial.birthdays, []);
  const birthdayResponse = await request('/api/records/birthdays', 'POST', { name: 'Anna', day: 7, month: 10, birthYear: 1990, memberId: initial.members[0].id });
  assert.equal(birthdayResponse.status, 201); const birthday = await birthdayResponse.json();
  const login = await request('/api/login', 'POST', { password: 'test-password-2026' }), secondCookie = login.headers.get('set-cookie').split(';')[0];
  const second = await (await request('/api/state', 'GET', undefined, { Cookie: secondCookie })).json(); assert.equal(second.birthdays[0].id, birthday.id); assert.equal(second.events.length, 0);
  const exported = await (await request('/api/export')).json(); assert.equal(exported.birthdays[0].birthYear, 1990); assert.equal(exported.version, '0.3.0');
  assert.equal((await request('/api/recipes/import', 'POST', { url: 'https://rezepte.example/pasta' }, { Origin: 'https://foreign.example' })).status, 403); assert.equal(imports, 0);
  const previewResponse = await request('/api/recipes/import', 'POST', { url: 'https://rezepte.example/pasta' }); assert.equal(previewResponse.status, 200);
  const preview = await previewResponse.json(); assert.equal(preview.recipe.sourceUrl, 'https://rezepte.example/pasta'); assert.equal(preview.recipe.ingredients[0].quantity, 400);
  assert.equal(app.store.all('recipes').length, 0); assert.equal(imports, 1);
  const savedResponse = await request('/api/records/recipes', 'POST', preview.recipe); assert.equal(savedResponse.status, 201);
  const saved = await savedResponse.json();
  assert.equal((await request('/api/records/meals', 'POST', { date: '2026-10-05', recipeId: saved.id, servings: 2 })).status, 201);
  assert.equal((await request('/api/shopping/generate', 'POST', { week: '2026-10-05' })).status, 200);
  assert.equal(app.store.all('items')[0].quantity, 200); assert.equal(app.store.all('items')[0].title, 'Nudeln');
  assert.equal((await request('/birthdays.js')).status, 200);
  assert.equal((await request('/api/records/birthdays/' + birthday.id, 'DELETE', { _rev: birthday._rev })).status, 200);
  assert.equal(app.store.state().birthdays.length, 0);
});
